#!/usr/bin/env bash

# Ask for confirmation
cdialog () {
    yad --title='Confirm?' --center --fixed --undecorated --button=Yes:0 --button=No:1 --text="You sure you wanna $1?" --text-align=center --align=center --justify=center --buttons-layout=center
}

cdialog "$1"

if [[ "$?" == 0 ]]; then
    sleep 0.25s
    if [[ "$1" == 'shutdown' ]]; then
        systemctl poweroff
    elif [[ "$1" == 'reboot' ]]; then
        systemctl reboot
    elif [[ "$1" == 'hibernate' ]]; then
        playerctl --all-players stop
        ~/.scripts/lock
        sleep 0.5s
        systemctl suspend-then-hibernate
    elif [[ "$1" == 'lock' ]]; then
        ~/.scripts/lock
    elif [[ "$1" == 'suspend' ]]; then
        playerctl --all-players stop
        ~/.scripts/lock
        sleep 0.5s
        systemctl suspend
    elif [[ "$1" == 'logout' ]]; then
        hyprctl dispatch exit none
    fi
else
    exit
fi
